# -*- coding: utf-8 -*-
"""Mundada_Siddhi_112684006_hw4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vS7xRMDE2XLUCjBWd3FD8R0OElQLFoy4

# CSE527 Homework 4
**Due date: 23:59 on Nov. 5, 2019 (Thuesday)**

In this semester, we will use Google Colab for the assignments, which allows us to utilize resources that some of us might not have in their local machines such as GPUs. You will need to use your Stony Brook (*.stonybrook.edu) account for coding and Google Drive to save your results.

## Google Colab Tutorial
---
Go to https://colab.research.google.com/notebooks/, you will see a tutorial named "Welcome to Colaboratory" file, where you can learn the basics of using google colab.

Settings used for assignments: ***Edit -> Notebook Settings -> Runtime Type (Python 3)***.


## Description
---
This project is an introduction to deep learning tools for computer vision. You will design and train deep convolutional networks for scene recognition using [PyTorch](http://pytorch.org). You can visualize the
structure of the network with [mNeuron] (http://vision03.csail.mit.edu/cnn_art/index.html)

Remember Homework 3: Scene recognition with bag of words. You worked hard to design a bag of features representations that achieved 60% to 70% accuracy (most likely) on 16-way scene classification. We're going to attack the same task with deep learning and get higher accuracy. Training from scratch won't work quite as well as homework 3 due to the insufficient amount of data, fine-tuning an existing network will work much better than homework 3.

In Problem 1 of the project you will train a deep convolutional network from scratch to recognize scenes. The starter codes gives you methods to load data and display them. You will need to define a simple network architecture and add jittering, normalization, and regularization to increase recognition accuracy to 50, 60, or perhaps 70%. Unfortunately, we only have 2,400 training examples so it doesn't seem possible to train a network from scratch which outperforms hand-crafted features

For Problem 2 you will instead fine-tune a pre-trained deep network to achieve about 85% accuracy on the task. We will use the pretrained AlexNet network which was not trained to recognize scenes at all. 

These two approaches represent the most common approaches to recognition problems in computer vision today -- train a deep network from scratch if you have enough data (it's not always obvious whether or not you do), and if you cannot then instead fine-tune a pre-trained network.

There are 2 problems in this homework with a total of 110 points including 10 bonus points. Be sure to read **Submission Guidelines** below. They are important. For the problems requiring text descriptions, you might want to add a markdown block for that.

## Dataset
---
Save the [dataset(click me)](https://drive.google.com/open?id=1NWC3TMsXSWN2TeoYMCjhf2N1b-WRDh-M) into your working folder in your Google Drive for this homework. <br>
Under your root folder, there should be a folder named "data" (i.e. XXX/Surname_Givenname_SBUID/data) containing the images.
**Do not upload** the data subfolder before submitting on blackboard due to size limit. There should be only one .ipynb file under your root folder Surname_Givenname_SBUID.

## Some Tutorials (PyTorch)
---
- You will be using PyTorch for deep learning toolbox (follow the [link](http://pytorch.org) for installation).
- For PyTorch beginners, please read this [tutorial](http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) before doing your homework.
- Feel free to study more tutorials at http://pytorch.org/tutorials/.
- Find cool visualization here at http://playground.tensorflow.org.


## Starter Code
---
In the starter code, you are provided with a function that loads data into minibatches for training and testing in PyTorch.
"""

# import packages here
import cv2
import numpy as np
import matplotlib.pyplot as plt
import glob
import random 
import time
import torch
import torchvision
import torchvision.transforms as transforms
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
from skimage.transform import rotate

# Mount your google drive where you've saved your assignment folder
from google.colab import drive
drive.mount('/content/gdrive')

# Set your working directory (in your google drive)
# Note that 'gdrive/My Drive/Y2019Fall/CSE-527-Intro-To-Computer-Vision/hw4' is just an example, 
#   change it to your specific homework directory.
cd '//content/gdrive/My Drive/CSE527_HW4_Fall19'

class_names = [name[13:] for name in glob.glob('./data/train/*')]
class_names = dict(zip(range(len(class_names)), class_names))
print("class_names: %s " % class_names)
n_train_samples = 150
n_test_samples = 50



def img_norm(img):
  #
  # Write your code here
   return((img - img.mean()) / img.std())# normalize img pixels to [-1, 1]
  #

def load_dataset(path, img_size, num_per_class=-1, batch_num=1, shuffle=False, augment=False, is_color=False,
                rotate_90=False, zero_centered=False):
    
    data = []
    labels = []
    
    if is_color:
        channel_num = 3
    else:
        channel_num = 1
        
    # read images and resizing
    for id, class_name in class_names.items():
        print("Loading images from class: %s" % id)
        img_path_class = glob.glob(path + class_name + '/*.jpg')
        if num_per_class > 0:
            img_path_class = img_path_class[:num_per_class]
        labels.extend([id]*len(img_path_class))
        for filename in img_path_class:
            if is_color:
                img = cv2.imread(filename)
            else:
                img = cv2.imread(filename, 0)
            
            # resize the image
            img = cv2.resize(img, img_size, cv2.INTER_LINEAR)
            
            if is_color:
                img = np.transpose(img, [2, 0, 1])
            
            # norm pixel values to [-1, 1]
            data.append(img_norm(img))
            
    #
    # Write your Data Augmentation code here
    # mirroring
    if augment:
        aug_data1 = [np.flip(img, 1) for img in data]
        data.extend(aug_data1)
        labels.extend(labels)
    #
    if rotate_90:
        aug_data = [rotate(img, 1) for img in data]
        data.extend(aug_data)
        labels.extend(labels)


    #
    # Write your Data Normalization code here
    # norm data to zero-centered
    if zero_centered:
      for img in data:
        img=img-img.mean()
     
    # randomly permute (this step is important for training)
    if shuffle:
        bundle = list(zip(data, labels))
        random.shuffle(bundle)
        data, labels = zip(*bundle)
    
    # divide data into minibatches of TorchTensors
    if batch_num > 1:
        batch_data = []
        batch_labels = []
        
        print(len(data))
        print(batch_num)
        
        for i in range(int(len(data) / batch_num)):
            minibatch_d = data[i*batch_num: (i+1)*batch_num]
            minibatch_d = np.reshape(minibatch_d, (batch_num, channel_num, img_size[0], img_size[1]))
            batch_data.append(torch.from_numpy(minibatch_d))

            minibatch_l = labels[i*batch_num: (i+1)*batch_num]
            batch_labels.append(torch.LongTensor(minibatch_l))
        data, labels = batch_data, batch_labels 
    
    return zip(batch_data, batch_labels)

# load data into size (64, 64)
img_size = (64, 64)
batch_num = 50 
# training sample number per batch

# load training dataset
trainloader_small = list(load_dataset('./data/train/', img_size, batch_num=batch_num, shuffle=True, 
                                      augment=True, zero_centered=True))
train_num = len(trainloader_small)
print("Finish loading %d minibatches(=%d) of training samples." % (train_num, batch_num))

# load testing dataset
testloader_small = list(load_dataset('./data/test/', img_size, num_per_class=50, batch_num=batch_num))
test_num = len(testloader_small)
print("Finish loading %d minibatches(=%d) of testing samples." % (test_num, batch_num))

# show some images
def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    if len(npimg.shape) > 2:
        npimg = np.transpose(img, [1, 2, 0])
    plt.figure
    plt.imshow(npimg, 'gray')
    plt.show()
img, label = trainloader_small[0][0][11][0], trainloader_small[0][1][11]
label = int(np.array(label))
print(class_names[label])
imshow(img)

"""## Problem 1: Training a Network From Scratch
{Part 1: 35 points} Gone are the days of hand designed features. Now we have end-to-end learning in which a highly non-linear representation is learned for our data to maximize our objective (in this case, 16-way classification accuracy). Instead of 70% accuracy we can now recognize scenes with... 25% accuracy. OK, that didn't work at all. Try to boost the accuracy by doing the following:

**Data Augmentation**: We don't have enough training data, let's augment the training data.
If you left-right flip (mirror) an image of a scene, it never changes categories. A kitchen doesn't become a forest when mirrored. This isn't true in all domains — a "d" becomes a "b" when mirrored, so you can't "jitter" digit recognition training data in the same way. But we can synthetically increase our amount of training data by left-right mirroring training images during the learning process.
[link text](https://)
After you implement mirroring, you should notice that your training error doesn't drop as quickly. That's actually a good thing, because it means the network isn't overfitting to the 2,400 original training images as much (because it sees 4,800 training images now, although they're not as good as 4,800 truly independent samples). Because the training and test errors fall more slowly, you may need more training epochs or you may try modifying the learning rate. You should see a roughly 10% increase in accuracy by adding mirroring. You are **required** to implement mirroring as data augmentation for this part.

You can try more elaborate forms of jittering -- zooming in a random amount, rotating a random amount, taking a random crop, etc. These are not required, you might want to try these in the bonus part.

**Data Normalization**: The images aren't zero-centered. One simple trick which can help a lot is to subtract the mean from every image. It would arguably be more proper to only compute the mean from the training images (since the test/validation images should be strictly held out) but it won't make much of a difference. After doing this you should see another 15% or so increase in accuracy. This part is **required**.

**Network Regularization**: Add dropout layer. If you train your network (especially for more than the default 30 epochs) you'll see that the training error can decrease to zero while the val top1 error hovers at 40% to 50%. The network has learned weights which can perfectly recognize the training data, but those weights don't generalize to held out test data. The best regularization would be more training data but we don't have that. Instead we will use dropout regularization.

What does dropout regularization do? It randomly turns off network connections at training time to fight overfitting. This prevents a unit in one layer from relying too strongly on a single unit in the previous layer. Dropout regularization can be interpreted as simultaneously training many "thinned" versions of your network. At test, all connections are restored which is analogous to taking an average prediction over all of the "thinned" networks. You can see a more complete discussion of dropout regularization in this [paper](https://www.cs.toronto.edu/~hinton/absps/JMLRdropout.pdf).

The dropout layer has only one free parameter — the dropout rate — the proportion of connections that are randomly deleted. The default of 0.5 should be fine. Insert a dropout layer between your convolutional layers. In particular, insert it directly before your last convolutional layer. Your test accuracy should increase by another 10%. Your train accuracy should decrease much more slowly. That's to be expected — you're making life much harder for the training algorithm by cutting out connections randomly. 

If you increase the number of training epochs (and maybe decrease the learning rate) you should be able to achieve around 50% test accuracy. In this part, you are **required** to add dropout layer to your network.

Please give detailed descriptions of your network layout in the following format:<br>
Data augmentation: [descriptions]<br>
Data normalization: [descriptions]<br>
Layer 1: [layer_type]: [Parameters]<br>
Layer 2: [layer_type]: [Parameters]<br>
...<br>
Then report the final accuracy on test set and time consumed for training and testing separately.

{Part 2: 15 points} Try **three techniques** taught in the class to increase the accuracy of your model. Such as increasing training data by randomly rotating training images, adding batch normalization, different activation functions (e.g., sigmoid) and model architecture modification. Note that too many layers can do you no good due to insufficient training data. Clearly describe your method and accuracy increase/decrease for each of the three techniques.
"""

# ==========================================
#       Define Network Architecture
# ==========================================
#Network1 with data augmentation,data normalization and network regularisation

class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.drop_out = nn.Dropout()
        self.fc1 = nn.Linear(16 * 16 * 64, 16)

    def forward(self, x):
      output = self.layer1(x)
      output = self.layer2(output)
      output = output.reshape(output.size(0), -1)
      output = self.drop_out(output)
      output = self.fc1(output)

      return output

import torch
torch.cuda.current_device()
device=torch.device('cuda:0')

# ==========================================
#         Optimize/Train Network
# ==========================================
# create a stochastic gradient descent optimizer
import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
model = ConvNet()
model.to(device)
# Loss and optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(model.parameters(), lr=0.001)
n_epochs=40

# Train the model
total_step = len(trainloader_small)
ll = []
acc = []
for epoch in range(n_epochs):
    for i, (images, labels) in enumerate(trainloader_small):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)

        loss = crit(outputs, labels)
        ll.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc.append(correct / total)

        if (i + 1) % 50 == 0:
            print('Epoch [{}/{}],  Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, n_epochs,  loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))
print('Training time',t)

# ==========================================
#            Evaluating Network
# ==========================================
import datetime
from datetime import timedelta
import time
time1=time.time()
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_small:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Testing time',t)

#Network2
#Batch normalization

class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.drop_out = nn.Dropout()
        self.fc1 = nn.Linear(16 * 16 * 64, 16)
        self.fc1_bn = nn.BatchNorm1d(16*16*64)

    def forward(self, x):
      output = self.layer1(x)
      output = self.layer2(output)
      output = output.reshape(output.size(0), -1)
      output = self.drop_out(output)
      output = self.fc1_bn(output)
      output = self.fc1(output)
      return output

import torch
torch.cuda.current_device()
device=torch.device('cuda:0')

# ==========================================
#         Optimize/Train Network
# ==========================================
# create a stochastic gradient descent optimizer
import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
model = ConvNet()
model.to(device)
# Loss and optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(model.parameters(), lr=0.001)
n_epochs=40

# Train the model
total_step = len(trainloader_small)
ll = []
acc = []
for epoch in range(n_epochs):
    for i, (images, labels) in enumerate(trainloader_small):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)

        loss = crit(outputs, labels)
        ll.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc.append(correct / total)

        if (i + 1) % 50 == 0:
            print('Epoch [{}/{}],  Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, n_epochs, loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training time',t)

# ==========================================
#            Evaluating Network
# ==========================================
import datetime
from datetime import timedelta
import time
time1=time.time()
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_small:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))
print('Testing time',t)

#Network 3
#Tanh activation function
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=5, stride=1, padding=2),
            nn.Tanh(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=2),
            nn.Tanh(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.drop_out = nn.Dropout()
        self.fc1 = nn.Linear(16 * 16 * 64, 16)

    def forward(self, x):
      output = self.layer1(x)
      output = self.layer2(output)
      output = output.reshape(output.size(0), -1)
      output = self.drop_out(output)
      output = self.fc1(output)
      return output

# ==========================================
#         Optimize/Train Network
# ==========================================
# create a stochastic gradient descent optimizer
import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
model = ConvNet()
model.to(device)
# Loss and optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(model.parameters(), lr=0.001)
n_epochs=40

# Train the model
total_step = len(trainloader_small)
ll = []
acc = []
for epoch in range(n_epochs):
    for i, (images, labels) in enumerate(trainloader_small):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        loss = crit(outputs, labels)
        ll.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc.append(correct / total)

        if (i + 1) % 50 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, n_epochs,  loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training time',t)

# ==========================================
#            Evaluating Network
# ==========================================
import datetime
from datetime import timedelta
import time
time1=time.time()
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_small:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))
print('Testing time',t)

#Network 4
#Rotations

# load data into size (64, 64)
from skimage.transform import rotate

img_size = (64, 64)
batch_num = 50 
# training sample number per batch

# load training dataset
trainloader_small = list(load_dataset('./data/train/', img_size, batch_num=batch_num, shuffle=True, 
                                      augment=False, zero_centered=True,rotate_90=True))
train_num = len(trainloader_small)
print("Finish loading %d minibatches(=%d) of training samples." % (train_num, batch_num))

# load testing dataset
testloader_small = list(load_dataset('./data/test/', img_size, num_per_class=50, batch_num=batch_num))
test_num = len(testloader_small)
print("Finish loading %d minibatches(=%d) of testing samples." % (test_num, batch_num))

#rotation function
import torchvision.transforms.functional as TF
import random


class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2))
        self.drop_out = nn.Dropout()
        self.fc1 = nn.Linear(16 * 16 * 64, 16)

    def forward(self, x):
      output = self.layer1(x)
      output = self.layer2(output) 
      output = output.reshape(output.size(0), -1)
      output = self.drop_out(output)
      output = self.fc1(output)
      return output

# ==========================================
#         Optimize/Train Network
# ==========================================
# create a stochastic gradient descent optimizer
import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
model = ConvNet()
model.to(device)
# Loss and optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(model.parameters(), lr=0.001)
n_epochs=40

# Train the model
total_step = len(trainloader_small)
ll = []
acc = []
for epoch in range(n_epochs):
    for i, (images, labels) in enumerate(trainloader_small):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        loss = crit(outputs, labels)
        ll.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc.append(correct / total)

        if (i + 1) % 50 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, n_epochs, loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training time',t)

# ==========================================
#            Evaluating Network
# ==========================================
import datetime
from datetime import timedelta
import time
time1=time.time()
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_small:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Testing time',t)

"""## Problem 2: Fine Tuning a Pre-Trained Deep Network
{Part 1: 30 points} Our convolutional network to this point isn't "deep". Fortunately, the representations learned by deep convolutional networks is that they generalize surprisingly well to other recognition tasks. 

But how do we use an existing deep network for a new recognition task? Take for instance,  [AlexNet](http://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks) network has 1000 units in the final layer corresponding to 1000 ImageNet categories.

**Strategy A**: One could use those 1000 activations as a feature in place of a hand crafted feature such as a bag-of-features representation. You would train a classifier (typically a linear SVM) in that 1000 dimensional feature space. However, those activations are clearly very object specific and may not generalize well to new recognition tasks. It is generally better to use the activations in slightly earlier layers of the network, e.g. the 4096 activations in the last 2nd fully-connected layer. You can often get away with sub-sampling those 4096 activations considerably, e.g. taking only the first 200 activations. 

**Strategy B**: *Fine-tune* an existing network. In this scenario you take an existing network, replace the final layer (or more) with random weights, and train the entire network again with images and ground truth labels for your recognition task. You are effectively treating the pre-trained deep network as a better initialization than the random weights used when training from scratch. When you don't have enough training data to train a complex network from scratch (e.g. with the 16 classes) this is an attractive option. Fine-tuning can work far better than Strategy A of taking the activations directly from an pre-trained CNN. For example, in [this paper](http://www.cc.gatech.edu/~hays/papers/deep_geo.pdf) from CVPR 2015, there wasn't enough data to train a deep network from scratch, but fine tuning led to 4 times higher accuracy than using off-the-shelf networks directly.

You are required to implement **Strategy B** to fine-tune a pre-trained **AlexNet** for this scene classification task. You should be able to achieve performance of 85% approximately. It takes roughly 35~40 minutes to train 20 epoches with AlexNet.

Please provide detailed descriptions of:<br>
(1) which layers of AlexNet have been replaced<br>
(2) the architecture of the new layers added including activation methods (same as problem 1)<br>
(3) the final accuracy on test set along with time consumption for both training and testing <br>

{Part 2: 20 points} Implement Strategy A where you use the activations of the pre-trained network as features to train one-vs-all SVMs for your scene classification task. Report the final accuracy on test set along with time consumption for both training and testing.

{Bonus: 10 points} Bonus will be given to those who fine-tune the [VGG network](https://pytorch.org/docs/stable/_modules/torchvision/models/vgg.html) [paper](https://arxiv.org/pdf/1409.1556.pdf) and compare performance with AlexNet. Explain why VGG performed better or worse.

**Hints**:
- Many pre-trained models are available in PyTorch at [here](http://pytorch.org/docs/master/torchvision/models.html).
- For fine-tuning pretrained network using PyTorch, please read this [tutorial](http://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html).
"""

#PART 1
#Startegy B
# reload data with a larger size
img_size = (224, 224)
batch_num = 50 # training sample number per batch 

# load training dataset
trainloader_large = list(load_dataset('./data/train/', img_size, batch_num=batch_num, shuffle=True, 
                                      augment=False, is_color=True,rotate_90=False, zero_centered=True))
train_num = len(trainloader_large)
print("Finish loading %d minibatches(=%d) of training samples." % (train_num, batch_num))

# load testing dataset
testloader_large = list(load_dataset('./data/test/', img_size, num_per_class=50, batch_num=batch_num, is_color=True))
test_num = len(testloader_large)
print("Finish loading %d minibatches(=%d) of testing samples." % (test_num, batch_num))

# ==========================================
#       Fine-Tune Pretrained Network
# ==========================================
import torchvision.models as models
alexnet = models.alexnet(pretrained=True)

#Defining the parameters
num_epochs = 20
num_classes = 16
batch_size = 50
learning_rate = 0.001

num_features = alexnet.classifier[6].in_features
features = list(alexnet.classifier.children())[:-1]

features.extend([nn.Linear(num_features,num_classes)])
alexnet.classifier = nn.Sequential(*features)
print(alexnet.classifier)

import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
alexnet.to(device)
# Loss and optimizer

num_epochs=40
#Defining the Loss and Optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(alexnet.parameters(), lr=learning_rate, momentum=0.9)
# Train the model
total_step = len(trainloader_large)
ll = []
acc = []
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(trainloader_large):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = alexnet(images)
        loss = crit(outputs, labels)
        ll.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc.append(correct / total)

        if (i + 1) % 30 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, num_epochs,  loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training time',t)

import datetime
import time
from datetime import timedelta
time1=time.time()
alexnet.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_large:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = alexnet(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Testing time',t)

#PART B
#Strategy A
# reload data with a larger size
img_size = (224, 224)
batch_num = 50 # training sample number per batch 

# load training dataset
trainloader_large = list(load_dataset('./data/train/', img_size, batch_num=batch_num, shuffle=True, 
                                      augment=False, is_color=True,rotate_90=False, zero_centered=True))
train_num = len(trainloader_large)
print("Finish loading %d minibatches(=%d) of training samples." % (train_num, batch_num))

# load testing dataset
testloader_large = list(load_dataset('./data/test/', img_size, num_per_class=50, batch_num=batch_num, is_color=True))
test_num = len(testloader_large)
print("Finish loading %d minibatches(=%d) of testing samples." % (test_num, batch_num))

import datetime
import time
from datetime import timedelta
import torchvision.models as models

time1=time.time()
alexnet = models.alexnet(pretrained=True)
f=[]
l=[]
#Defining the parameters
# convert all the layers to list and remove the last one
for i, (images, labels) in enumerate(trainloader_large):
    outputs = alexnet(images.float())
    data = np.squeeze((outputs.detach().tolist()))
    f.extend(data)
    l.extend(labels.tolist())

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training time',t)

import datetime
import time
from datetime import timedelta

time1=time.time()
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5,C=.01,multi_class='ovr')
clf.fit(f,l)  

time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Time take to fit SVM',t)

from sklearn.metrics import accuracy_score
import datetime
import time
from datetime import timedelta

time1=time.time()
#Defining the parameters
# convert all the layers to list and remove the last one
l=[]
l1=[]
for i, (images, labels) in enumerate(testloader_large):
    outputs = alexnet(images.float())
    data = np.squeeze((outputs.detach().tolist()))
    # nu_ftrs = alexnet.classifier[6]
    # features = list(alexnet.classifier.children())[:-1]
    #images = list(outputs.classifier.children())[:-1]
    l1.extend(clf.predict(data))
    l.extend(labels.tolist())

acc=accuracy_score(l1,l)
print("Accuracy by using StrategyA:",acc*100)
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Testing time',t)

#Bonus part
#VGG
# reload data with a larger size
img_size = (224, 224)
batch_num = 50 # training sample number per batch 

# load training dataset
trainloader_large = list(load_dataset('./data/train/', img_size, batch_num=batch_num, shuffle=True, 
                                      augment=False, is_color=True,rotate_90=False, zero_centered=True))
train_num = len(trainloader_large)
print("Finish loading %d minibatches(=%d) of training samples." % (train_num, batch_num))

# load testing dataset
testloader_large = list(load_dataset('./data/test/', img_size, num_per_class=50, batch_num=batch_num, is_color=True))
test_num = len(testloader_large)
print("Finish loading %d minibatches(=%d) of testing samples." % (test_num, batch_num))

# ==========================================
#       Fine-Tune Pretrained Network
# ==========================================
import torchvision.models as models
vgg = models.vgg19(pretrained=True)

#Defining the parameters
num_epochs = 20
num_classes = 16
batch_size = 50
learning_rate = 0.001

# convert all the layers to list and remove the last one
num_features = vgg.classifier[6].in_features

features = list(vgg.classifier.children())[:-1]

features.extend([nn.Linear(num_features,num_classes)])
vgg.classifier = nn.Sequential(*features)
print(vgg.classifier)

import datetime
import time
from datetime import timedelta
import torch.optim as optim
time1=time.time()
vgg.to(device)
# Loss and optimizer
#Defining the Loss and Optimizer
crit = nn.CrossEntropyLoss()
opt = torch.optim.SGD(vgg.parameters(), lr=learning_rate, momentum=0.9)
n_epochs=40

# Train the model
total_step = len(trainloader_large)
loss_list = []
acc_list = []
for epoch in range(n_epochs):
    for i, (images, labels) in enumerate(trainloader_large):
        # Run the forward pass
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = vgg(images)
        loss = crit(outputs, labels)
        loss_list.append(loss.item())

        # Backprop and perform Adam optimisation
        opt.zero_grad()
        loss.backward()
        opt.step()

        # Track the accuracy
        total = labels.size(0)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == labels).sum().item()
        acc_list.append(correct / total)

        if (i + 1) % 30 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}, Accuracy: {:.2f}%'
                  .format(epoch + 1, n_epochs,  loss.item(),
                          (correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Training Time',t)

import datetime
import time
from datetime import timedelta

time1=time.time()
vgg.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader_large:
        images=images.to(device,dtype=torch.float)
        labels=labels.to(device,dtype=torch.long)
        outputs = vgg(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format((correct / total) * 100))
time2=time.time()
time=time2-time1
t=str(datetime.timedelta(seconds=time))

print('Testing time',t)

"""# **REPORT**
Problem 1: Training a Network From Scratch

Part 1:

Network 1: 
I have implemented a convolutional neural network in this part.

Detailed decription of the network:

Data Augmentation: In this part I have augmented the training data with the mirror images of the training data.

Data Normalization: This part is to make the images zero-centered and this can be done by subtracting the mean of image from the training images.

Network Regularization: In this part we need to add a dropout layer to prevent overfitting of data.

Convolutional Layer1 with input_channels=1,output_channel=32,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Convolutional Layer2 with input_channels=32,output_channel=64,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Linear Layer with input of 16x16x64x16

Accuracies and time taken by this network:

Epochs:40

Training time:25 sec

Training accuracy: 66%

Testing time: .02 secs

Testing accuracy: 52.75%


Part 2:

In this part I tried to compare the accuracies by trying different activation functions, performing batch normalization and rotating the training images and comparing these accuracies with the base model.

Network 2: With batch normalisation

Decription of the network:

Batch normalisation: In this part the batches created are normalised because we donot test the whole data together hence we need to keep the range of the batches uniform.This is done by using BatchNorm1d.

Convolutional Layer1 with input_channels=1,output_channel=32,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Convolutional Layer2 with input_channels=32,output_channel=64,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Linear Layer with input of 16x16x64x16

Accuracies and time taken by this network:

Epochs:40

Training time:25.95 sec

Training accuracy: ~100%

Testing time: .02 secs

Testing accuracy: 65%

The accuracy increased by 12.25%.

Network 3: Using different activation functions

Decription of the network:

Convolutional Layer1 with input_channels=1,output_channel=32,kernel size=5x5,Tanh activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Convolutional Layer2 with input_channels=32,output_channel=64,kernel size=5x5,Tanh activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Linear Layer with input of 16x16x64x16

Accuracies and time taken by this network:

Using Tanh activation function:

Epochs:40

Training time:25.56 sec

Training accuracy: 60%

Testing time: .02 secs

Testing accuracy: 47.75%

Using sigmoid activation function:

Training time:25.56 sec

Training accuracy: 25%

Testing time: .02 secs

Testing accuracy: 18.5%

By comparing the 3 activation function we came to the conclusion that ReLU gives the best accuracy for our network.

Network 4: Rotation Augmentation

Decription of the network:

Rotation Augmentation: In this part we rotated the training images and augmented it to the training dataset.

Convolutional Layer1 with input_channels=1,output_channel=32,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Convolutional Layer2 with input_channels=32,output_channel=64,kernel size=5x5,ReLU activation function,stride of 1x1 and padding of 2x2,MaxPool layer with stride of 2x2 and kernel size 2x2. 

Linear Layer with input of 16x16x64x16

Accuracies and time taken by this network:

Epochs:40

Training time:25.4 sec

Training accuracy: 74%

Testing time: .02 secs

Testing accuracy: 45.75%

Problem 2: Fine-Tuning a Pre-trained Deep Network

Part 1:Strategy B

Fine tune our network to alexnet.
Network:
 Dropout(p=0.5, inplace=False)
  (1): Linear(in_features=9216, out_features=4096, bias=True)
  (2): ReLU(inplace=True)
  (3): Dropout(p=0.5, inplace=False)
  (4): Linear(in_features=4096, out_features=4096, bias=True)
  (5): ReLU(inplace=True)
  (6): Linear(in_features=4096, out_features=16, bias=True)
)

Epochs:40

Training time:1min 28sec

Training accuracy: 100%

Testing time: .22 secs

Testing accuracy: 89.5%

Part 2: Strategy A

In this part, out_features=1000 .Now we fit the outfeatures and labels into SVM and then test the testing images.

Epochs:40

Training time:1min 01sec

Training accuracy: 100%

Testing time: .10 secs

Testing accuracy: 78.5%

Bonus Part:Fine tune our network to vggnet.

Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=16, bias=True)

Epochs:40

Training time:15min 34sec

Training accuracy: 100%

Testing time: .01 secs

Testing accuracy: 94.75%

## Submission guidelines
---
Extract the downloaded .zip file to a folder of your preference. The input and output paths are predefined and **DO NOT** change them, (we assume that 'Surname_Givenname_SBUID_hw4' is your working directory, and all the paths are relative to this directory).  The image read and write functions are already written for you. All you need to do is to fill in the blanks as indicated to generate proper outputs. **DO NOT** zip and upload the dataset on blackboard due to size limit.

When submitting your .zip file through blackboard, please
-- name your .zip file as **Surname_Givenname_SBUID_hw*.zip**.

This zip file should include:
```
Surname_Givenname_SBUID_hw*
        |---Surname_Givenname_SBUID_hw*.ipynb
        |---Surname_Givenname_SBUID_hw*.py
        |---Surname_Givenname_SBUID_hw*.pdf
```
where Surname_Givenname_SBUID_hw*.py is the Python code of Surname_Givenname_SBUID_hw*.ipynb, which can be dowloaded by File->Download .py.

For instance, student Michael Jordan should submit a zip file named "Jordan_Michael_111134567_hw4.zip" for homework4 in this structure:
```
Jordan_Michael_111134567_hw4
        |---Jordan_Michael_111134567_hw4.ipynb
        |---Jordan_Michael_111134567_hw4.py
        |---Jordan_Michael_111134567_hw4.pdf
```

The **Surname_Givenname_SBUID_hw*.pdf** should include a **google shared link** and **Surname_Givenname_SBUID_Pred*.pdf** should be your test set prediction file in the specified format. To generate the **google shared link**, first create a folder named **Surname_Givenname_SBUID_hw*** in your Google Drive with your Stony Brook account. The structure of the files in the folder should be exactly the same as the one you downloaded. If you alter the folder structures, the grading of your homework will be significantly delayed and possibly penalized.

Then right click this folder, click ***Get shareable link***, in the People textfield, enter two TA's emails: ***bo.cao.1@stonybrook.edu*** and ***sayontan.ghosh@stonybrook.edu***. Make sure that TAs who have the link **can edit**, ***not just*** **can view**, and also **uncheck** the **Notify people** box.

Colab has a good feature of version control, you should take advantage of this to save your work properly. However, the timestamp of the submission made in blackboard is the only one that we consider for grading. To be more specific, we will only grade the version of your code right before the timestamp of the submission made in blackboard. 

You are encouraged to post and answer questions on Piazza. Based on the amount of email that we have received in past years, there might be dealys in replying to personal emails. Please ask questions on Piazza and send emails only for personal issues.

Be aware that your code will undergo plagiarism check both vertically and horizontally. Please do your own work.

**Late submission penalty:** <br>
There will be a 10% penalty per day for late submission. However, you will have 4 days throughout the whole semester to submit late without penalty. Note that the grace period is calculated by days instead of hours. If you submit the homework one minute after the deadline, one late day will be counted. Likewise, if you submit one minute after the deadline, the 10% penaly will be imposed if not using the grace period.

<!--Write your report here in markdown or html-->
"""